In [1]:
# Load libraries
import os
import sys
import pickle
import pandas as pd
import numpy as np
import nltk
import re
import warnings
nltk.download('punkt')
nltk.download('stopwords')
import string
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC


[nltk_data] Error loading punkt: <urlopen error [Errno -3] Temporary
[nltk_data]     failure in name resolution>
[nltk_data] Error loading stopwords: <urlopen error [Errno -3]
[nltk_data]     Temporary failure in name resolution>


In [2]:
#import pandas as pd
#text = 'twitter_my_data.csv'
#df = pd.read_csv(text)
#df.shape, df.head()

In [3]:
#df.groupby('label').size()

In [4]:
# load dataset
text_file = 'Agent_Clf.csv'
data = pd.read_csv(text_file)
data.head()

text    label
0  to provide you with a world customer experienc...    <IVR>
1                      thanks for being online priya  <Agent>
2  to provide you the worlds large customer exper...    <IVR>
3  to provide you with a world class customer exp...    <IVR>
4  with constantly engather we provide you with t...    <IVR>

In [5]:
data.shape

(1078, 2)

In [6]:
data.head(10)

text       label
0  to provide you with a world customer experienc...       <IVR>
1                      thanks for being online priya     <Agent>
2  to provide you the worlds large customer exper...       <IVR>
3  to provide you with a world class customer exp...       <IVR>
4  with constantly engather we provide you with t...       <IVR>
5  ok thanks apart from this nothing i can expect...  <Customer>
6      yeah chalo thanks a lot ok ok welcome welcome  <Customer>
7                        theek hai perfect thank you  <Customer>
8          purpose ok thanks satish most welcome sir  <Customer>
9                                 yeah welcome ma'am     <Agent>

In [8]:
data.groupby('label').size()

label
<Agent>       421
<Customer>    414
<IVR>         243
dtype: int64

In [9]:
X = data.text
y = data.label

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state = 42)
print(X_train.shape)
print(X_test.shape)

(862,)
(216,)


# SVC

In [10]:
param_grid = {'C':[1,10,100,1000],'gamma':[1,0.1,0.001,0.0001], 'kernel':['linear','rbf']}

grid = GridSearchCV(SVC(),param_grid,refit = True, verbose=2)




pipe_line = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               ('clf', grid)
              ])
svc_fit = pipe_line.fit(X_train, y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=   0.1s
[CV] C=1, gamma=1, kernel=linear .....................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s


[CV] ...................... C=1, gamma=1, kernel=linear, total=   0.1s
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=   0.1s
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=   0.1s
[CV] C=1, gamma=1, kernel=linear .....................................
[CV] ...................... C=1, gamma=1, kernel=linear, total=   0.1s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=   0.1s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=   0.2s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] ......................... C=1, gamma=1, kernel=rbf, total=   0.1s
[CV] C=1, gamma=1, kernel=rbf ........................................
[CV] .

[CV] ...................... C=10, gamma=0.1, kernel=rbf, total=   0.1s
[CV] C=10, gamma=0.001, kernel=linear ................................
[CV] ................. C=10, gamma=0.001, kernel=linear, total=   0.1s
[CV] C=10, gamma=0.001, kernel=linear ................................
[CV] ................. C=10, gamma=0.001, kernel=linear, total=   0.1s
[CV] C=10, gamma=0.001, kernel=linear ................................
[CV] ................. C=10, gamma=0.001, kernel=linear, total=   0.1s
[CV] C=10, gamma=0.001, kernel=linear ................................
[CV] ................. C=10, gamma=0.001, kernel=linear, total=   0.1s
[CV] C=10, gamma=0.001, kernel=linear ................................
[CV] ................. C=10, gamma=0.001, kernel=linear, total=   0.1s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] .................... C=10, gamma=0.001, kernel=rbf, total=   0.1s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] .

[CV] .................. C=100, gamma=0.0001, kernel=rbf, total=   0.1s
[CV] C=100, gamma=0.0001, kernel=rbf .................................
[CV] .................. C=100, gamma=0.0001, kernel=rbf, total=   0.1s
[CV] C=100, gamma=0.0001, kernel=rbf .................................
[CV] .................. C=100, gamma=0.0001, kernel=rbf, total=   0.1s
[CV] C=1000, gamma=1, kernel=linear ..................................
[CV] ................... C=1000, gamma=1, kernel=linear, total=   0.1s
[CV] C=1000, gamma=1, kernel=linear ..................................
[CV] ................... C=1000, gamma=1, kernel=linear, total=   0.1s
[CV] C=1000, gamma=1, kernel=linear ..................................
[CV] ................... C=1000, gamma=1, kernel=linear, total=   0.1s
[CV] C=1000, gamma=1, kernel=linear ..................................
[CV] ................... C=1000, gamma=1, kernel=linear, total=   0.1s
[CV] C=1000, gamma=1, kernel=linear ..................................
[CV] .

[Parallel(n_jobs=1)]: Done 160 out of 160 | elapsed:   18.7s finished


In [11]:
grid.best_params_


{'C': 1, 'gamma': 1, 'kernel': 'rbf'}

In [27]:
SVC_pipeline = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               ('clf', SVC(kernel='rbf', gamma=1, C=1))
              ])
pipe_SVC = SVC_pipeline.fit(X_train, y_train)

from sklearn.metrics import classification_report
y_pred_SVC = pipe_SVC.predict(X_test)

print('test accuracy %s' % pipe_SVC.score(X_test, y_test))
print('train accuracy %s' % pipe_SVC.score(X_train, y_train))


print(classification_report(y_test, y_pred_SVC))

test accuracy 0.8287037037037037
train accuracy 0.9825986078886311
              precision    recall  f1-score   support

     <Agent>       0.85      0.76      0.80        93
  <Customer>       0.76      0.89      0.82        80
       <IVR>       0.97      0.86      0.91        43

    accuracy                           0.83       216
   macro avg       0.86      0.84      0.84       216
weighted avg       0.84      0.83      0.83       216



In [13]:
print(confusion_matrix(y_test, y_pred_SVC))

[[71 22  0]
 [ 8 71  1]
 [ 5  1 37]]


In [15]:
print((y_test != y_pred_SVC).sum())

37


# saving model and countvect in pickel for other purposes

In [22]:
SVC_pipeline = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               #('clf', SVC(kernel='rbf', gamma=1, C=1))
              ])
pipe_SVC_train = SVC_pipeline.fit(X_train)


X_train_trans = pipe_SVC_train.transform(X_train)
X_test_trans = pipe_SVC_train.transform(X_test)

In [23]:
classifier = SVC(kernel='rbf', gamma=1, C=1)
classifier.fit(X_train_trans, y_train)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [25]:
y_pred_SVC_1 = classifier.predict(X_test_trans)

In [29]:
print('test accuracy %s' % classifier.score(X_test_trans, y_test))
print('train accuracy %s' % classifier.score(X_train_trans, y_train))


print(classification_report(y_test, y_pred_SVC_1))

test accuracy 0.8287037037037037
train accuracy 0.9825986078886311
              precision    recall  f1-score   support

     <Agent>       0.85      0.76      0.80        93
  <Customer>       0.76      0.89      0.82        80
       <IVR>       0.97      0.86      0.91        43

    accuracy                           0.83       216
   macro avg       0.86      0.84      0.84       216
weighted avg       0.84      0.83      0.83       216



In [38]:
text_arr = pipe_SVC_train.transform(['message']).toarray()
classifier.predict(text_arr)

array(['<Customer>'], dtype=object)

In [40]:
# Creating a pickle file for the CountVectorizer
pickle.dump(pipe_SVC_train, open('count_vectorizer.pkl', 'wb'))

In [41]:
# Creating a pickle file for the Multinomial Naive Bayes model
filename = 'agent_cust_ivr_svc_model.pkl'
pickle.dump(classifier, open(filename, 'wb'))

# Multi_NB

In [12]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer


nb = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               ('clf', MultinomialNB(fit_prior=True, class_prior=None))
              ])
Multi_NB = nb.fit(X_train, y_train)

from sklearn.metrics import classification_report
y_pred_NB = Multi_NB.predict(X_test)

print('test accuracy %s' % Multi_NB.score(X_test, y_test))
print('train accuracy %s' % Multi_NB.score(X_train, y_train))

print(classification_report(y_test, y_pred_NB))

test accuracy 0.7824074074074074
train accuracy 0.8839907192575406
              precision    recall  f1-score   support

     <Agent>       0.74      0.76      0.75        93
  <Customer>       0.74      0.80      0.77        80
       <IVR>       1.00      0.79      0.88        43

   micro avg       0.78      0.78      0.78       216
   macro avg       0.83      0.78      0.80       216
weighted avg       0.79      0.78      0.78       216



In [13]:
print(confusion_matrix(y_test, y_pred_NB))

[[71 22  0]
 [16 64  0]
 [ 9  0 34]]


In [14]:
print((y_test != y_pred_NB).sum())

47


# LR

In [15]:
from sklearn.linear_model import LogisticRegression

lr_pipeline = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               ('clf', LogisticRegression(penalty='l1')),
              ])
lr_clf = lr_pipeline.fit(X_train, y_train)

from sklearn.metrics import classification_report
y_pred_lr = lr_clf.predict(X_test)

print('test accuracy %s' % lr_clf.score(X_test, y_test))
print('train accuracy %s' % lr_clf.score(X_train, y_train))

print(classification_report(y_test, y_pred_lr))

test accuracy 0.7268518518518519
train accuracy 0.7993039443155452
              precision    recall  f1-score   support

     <Agent>       0.71      0.69      0.70        93
  <Customer>       0.68      0.75      0.71        80
       <IVR>       0.87      0.77      0.81        43

   micro avg       0.73      0.73      0.73       216
   macro avg       0.75      0.74      0.74       216
weighted avg       0.73      0.73      0.73       216



/home/bukya/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/bukya/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [16]:
print((y_test != y_pred_lr).sum())

59


# KNN

In [17]:
#Import KNN

from sklearn.neighbors import KNeighborsClassifier
#knn_model = KNeighborsClassifier(n_neighbors=15)




#knn_model = knn_pipeline.fit(X_train, y_train)
from sklearn import preprocessing
for i in range(1,30):
    knn_pipeline = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               ('clf', KNeighborsClassifier(n_neighbors=i)),
              ])
    #knn = KNeighborsClassifier(n_neighbors = i)
    knn_model = knn_pipeline.fit(X_train, y_train)
    #model_knn = knn.fit(X_train, y_train)
    y_pred_knn = knn_model.predict(X_test)
    score = metrics.accuracy_score(y_pred_knn, y_test)
    print(i)
    print(score)





1
0.7638888888888888
2
0.7546296296296297
3
0.7314814814814815
4
0.7407407407407407
5
0.7407407407407407
6
0.7546296296296297
7
0.75
8
0.7407407407407407
9
0.7361111111111112
10
0.7314814814814815
11
0.75
12
0.7407407407407407
13
0.7222222222222222
14
0.7407407407407407
15
0.7314814814814815
16
0.75
17
0.7314814814814815
18
0.7546296296296297
19
0.7314814814814815
20
0.7453703703703703
21
0.7222222222222222
22
0.7453703703703703
23
0.7314814814814815
24
0.7314814814814815
25
0.7361111111111112
26
0.7546296296296297
27
0.7453703703703703
28
0.7314814814814815
29
0.7361111111111112


In [18]:
knn_pipeline = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               ('clf', KNeighborsClassifier(n_neighbors=1)),
              ])



knn_clf = knn_pipeline.fit(X_train, y_train)

from sklearn.metrics import classification_report
y_pred_knn = knn_clf.predict(X_test)

print('test accuracy %s' % knn_clf.score(X_test, y_test))
print('train accuracy %s' % knn_clf.score(X_train, y_train))

print(classification_report(y_test, y_pred_knn))

test accuracy 0.7638888888888888
train accuracy 0.9965197215777262
              precision    recall  f1-score   support

     <Agent>       0.76      0.76      0.76        93
  <Customer>       0.75      0.68      0.71        80
       <IVR>       0.80      0.93      0.86        43

   micro avg       0.76      0.76      0.76       216
   macro avg       0.77      0.79      0.78       216
weighted avg       0.76      0.76      0.76       216



In [19]:
print((y_test != y_pred_knn).sum())

51


# RFC

In [20]:
from sklearn.ensemble import RandomForestClassifier



rfc_pipeline = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               ('clf', RandomForestClassifier()),
              ])



rfc_clf = rfc_pipeline.fit(X_train, y_train)

from sklearn.metrics import classification_report
y_pred_rfc = rfc_clf.predict(X_test)

print('test accuracy %s' % rfc_clf.score(X_test, y_test))
print('train accuracy %s' % rfc_clf.score(X_train, y_train))

print(classification_report(y_test, y_pred_rfc))

test accuracy 0.7777777777777778
train accuracy 0.9918793503480279
              precision    recall  f1-score   support

     <Agent>       0.78      0.73      0.76        93
  <Customer>       0.73      0.78      0.75        80
       <IVR>       0.86      0.88      0.87        43

   micro avg       0.78      0.78      0.78       216
   macro avg       0.79      0.80      0.79       216
weighted avg       0.78      0.78      0.78       216



/home/bukya/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [21]:
print(confusion_matrix(y_test, y_pred_rfc))

[[68 22  3]
 [15 62  3]
 [ 4  1 38]]


In [22]:
print((y_test != y_pred_rfc).sum())

48


# LinearSVC

In [23]:
from sklearn.svm import LinearSVC
LSVC_pipeline = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               ('clf', LinearSVC()),
              ])
Lin_LSVC = LSVC_pipeline.fit(X_train, y_train)

from sklearn.metrics import classification_report
y_pred_LSVC = Lin_LSVC.predict(X_test)

print('test accuracy %s' % Lin_LSVC.score(X_test, y_test))
print('train accuracy %s' % Lin_LSVC.score(X_train, y_train))


print(classification_report(y_test, y_pred_LSVC))

test accuracy 0.8009259259259259
train accuracy 0.9825986078886311
              precision    recall  f1-score   support

     <Agent>       0.79      0.76      0.78        93
  <Customer>       0.77      0.80      0.79        80
       <IVR>       0.88      0.88      0.88        43

   micro avg       0.80      0.80      0.80       216
   macro avg       0.81      0.82      0.81       216
weighted avg       0.80      0.80      0.80       216



In [24]:
print(confusion_matrix(y_test, y_pred_LSVC))

[[71 19  3]
 [14 64  2]
 [ 5  0 38]]


In [25]:
print((y_test != y_pred_LSVC).sum())

43
